on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
    branches: [ "*" ]
    inputs:
      renew_cache:
        description: "Renew Cache"
        required: true
        default: "false"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Initialize
      run: |
        ./test.sh "Hello World."
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terminate
      run: |
        ./test.sh "Goodbye World."


